APP_CONTAINER := './ops/Dockerfile'
APP_COMPOSE := './ops/compose.yml'

APP_SERVICE := 'app'

#

build:
    docker build --file {{APP_CONTAINER}} --tag app:latest .

#

up:
    docker compose -f {{APP_COMPOSE}} up -d --remove-orphans

down:
    docker compose -f {{APP_COMPOSE}} down

logs:
    docker compose -f {{APP_COMPOSE}} logs --follow=true {{APP_SERVICE}}

restart: down up logs

# 

fmt:
    npx prettier ./minitwitter --write

fmt-check:
    npx prettier ./minitwitter --check
